services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/crypto?serverVersion=8.0.32&charset=utf8mb4"
      MESSENGER_TRANSPORT_DS: doctrine://default?auto_setup=0

  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_ROOT_PASSWORD: root
    container_name: database
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - database
    command: [ "php", "bin/console", "messenger:consume"]
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/crypto?serverVersion=8.0.32&charset=utf8mb4"
      MESSENGER_TRANSPORT_DS: doctrine://default?auto_setup=0